CREATE DATABASE routeApp;

USE routeApp;


CREATE TABLE admin(
	id INT(11) NOT NULL,
	fullname VARCHAR(60) NOT NULL,
	username VARCHAR(60) NOT NULL,
	password VARCHAR(100) NOT NULL
);

ALTER TABLE admin
	ADD PRIMARY KEY (id);

ALTER TABLE admin
	MODIFY id INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 2;


CREATE TABLE employee(
	id INT(11) NOT NULL,
	username VARCHAR(60) NOT NULL,
	password VARCHAR(100) NOT NULL,
	usertype VARCHAR(60) NOT NULL,
	user_id INT(11),
	CONSTRAINT fl_employee FOREIGN KEY(user_id) REFERENCES admin(id)
);

ALTER TABLE employee
	ADD PRIMARY KEY (id);

ALTER TABLE employee
	MODIFY id INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 2;

CREATE TABLE route(
	id INT(11) NOT NULL,
	fullname VARCHAR(60) NOT NULL,
	address VARCHAR(100) NOT NULL,
	route VARCHAR(60) NOT NULL,
	driver VARCHAR(60) NOT NULL,
	user_id INT(11)
	CONSTRAINT fl_route FOREIGN KEY(user_id) REFERENCES employee(id)

);

ALTER TABLE route
	ADD PRIMARY KEY (id);

ALTER TABLE route
	MODIFY id INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 2;